# Generated by Django 2.1 on 2020-08-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='bmi',
            field=models.FloatField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='weight',
            name='body_fat',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
    ]
